### PR TITLE
Bugfix/327 update tutorial

### PR DESCRIPTION
**Pull request by mitzimorris**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and open-source license: see below

#### Summary

Rewrite of the tutorial notebook distributed with CmdStanPy.
follow-up to issue https://github.com/stan-dev/cmdstanpy/issues/327

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by ahartikainen** [comment]
Hi, looks good.

I wonder if we should also create a minimal example (working from python)

e.g.

```
import json
import numpy as np
from cmdstanpy import CmdStanModel

# handle model
model_code = """
data {
    int N;
    real y[N];
}
parameters {
    real mu;
    real sigma;
}
model {
    mu ~ normal(0,1);
    sigma ~ normal(0,1);

    y ~ normal(mu, sigma);
}

model_path = "./linear_model.stan"

with open(model_path) as fh:
    print(model_code, file=fh)

# handle data
mu_real, sigma_real = 2, 3
data = {N: 100, x: sigma_real * np.random.randn(100) + mu_real}
data_path = "./linear_data.stan"

with open(data_path) as fh:
    json.dump(data, fh)

model = CmdStanModel(stan_file=model_path)
fit = model.sample(chains=4, data=data_path)
fit.summary()
```

**Comment by mitzimorris** [comment]
we've got a script checked into `test` which tests show progress.  a version of this, minus progress bar stuff, plus accessing variables whould be most useful.

**Comment by mitzimorris** [comment]
@ahartikainen  created script equivalent of tutorial notebook and checked it in - this OK?

**Review by ahartikainen — APPROVED** [review]
The script looks good

**Pull request merged**
