### PR TITLE
Feature/165 use pylint

### PR DESCRIPTION
**Pull request by mitzimorris**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and open-source license: see below

#### Summary
Using current version of `pylint` from PyPi:  pylint 2.4.4

- ran `pylint --generate-rcfile` utility, output as  `.pylintrc`
- added in disabled check from arviz `.pylintrc` file
- ran pylint on all cmdstanpy modules and either corrected the problem, or disabled the check either globally or locally.

Pylint found a few bugs in the error message strings, inefficiencies in the logging messages,  some unused variables, and missing docstrings.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):  Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by mitzimorris** [comment]
Still need to configure Travis to run pylint checks.

**Comment by mitzimorris** [comment]
reviewers, what are your thoughts on the list of disabled checks in file `.pyintrc`?

**Comment by mitzimorris** [comment]
cleanup disable list in `.pylintrc` - configured to ignore the following, given the current codebase:

```
disable=bad-continuation,
    consider-using-in,
    cyclic-import,
    fixme,
    import-outside-toplevel,
    no-else-break,
    no-else-return,
    protected-access,
    redefined-builtin,
    too-many-branches,
    too-many-locals
```

added a few 1 and 2-letter names to list of allowed names - allowing `fd` for file descriptors, using `e` not `ex` for exceptions.

```
good-names=i,
           j,
           k,
           c,
           e,
           fd,
           vs,
           x,
           xs,
           y,
           Run,
           _
```

allowing duplicated code chunks up to 25 lines - this is because the install scripts currently share some code.  leaving this for a different issue/PR.

**Comment by ahartikainen** [comment]
> allowing duplicated code chunks up to 25 lines - this is because the install scripts currently share some code. leaving this for a different issue/PR.

Yeah, this is a bit broken currently in pylint. I think after they fix it, we could just ignore those install files (they should be independent).

**Comment by wesbarnett** [comment]
I know I'm late to the discussion, but I saw that Travis already does linting checks with flake8. Will we be changing that?

**Comment by wesbarnett** [comment]
Oops, I see that is in #184

**Comment by wesbarnett** [comment]
One thing that stands out is that the max line length is at 100 in the new pylintrc, when previously we were using 80 with flake8. [PEP 8 gives guidance to limit to 79](https://www.python.org/dev/peps/pep-0008/#maximum-line-length).

**Pull request merged**
