### PR TITLE
cleanup/290-draws_as_dataframe

### PR DESCRIPTION
**Pull request by imadmali**
#### Submission Checklist

- [ ] Run unit tests
- [x] Declare copyright holder and open-source license: see below

#### Summary

Resolves issue #290 by renaming `draws_as_dataframe` to `draws_pd` and `_draws_as_df` to `_draws_pd`. Locally, the test `test_multi_proc` fails in this branch, but also in develop.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Imad Ali

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Review by mitzimorris — APPROVED** [review]
LGTM!

**Comment by mitzimorris** [comment]
>  Locally, the test test_multi_proc fails in this branch, but also in develop.

`test_multi_proc` is pretty brittle - what line does it fail at? 
it tries to see if a bunch of chains get spawned in parallel by checking whether or not the console messages are properly interleaved - but there are many reasons why this might happen, depending on the machine it's running on.

works on my machine, FWIW.

**Comment by imadmali** [comment]
It looks like it fails at line 306. Logs below. I guess my follow up question is how did my pull request pass CICD, if it failed on my local machine? Am I missing a dependency or something?

```
======================================================================
FAIL: test_multi_proc (__main__.SampleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test_sample.py", line 306, in test_multi_proc
    log.check_present(('cmdstanpy', 'DEBUG', expect))
  File "/Users/iali/.venv/cmdstanpy-dev/lib/python3.7/site-packages/testfixtures/logcapture.py", line 223, in check_present
    recursive=self.recursive_check)
  File "/Users/iali/.venv/cmdstanpy-dev/lib/python3.7/site-packages/testfixtures/comparison.py", line 684, in compare
    raise AssertionError(message)
AssertionError: sequence not as expected:

same:
()

expected:
(('cmdstanpy', 'DEBUG', 'total threads: 60'),)

actual:
(('cmdstanpy', 'DEBUG', 'total threads: 35'),
 ('cmdstanpy', 'INFO', 'start chain 1'),
 ('cmdstanpy', 'DEBUG', 'threads: 5'),
 ('cmdstanpy',
  'DEBUG',
  "sampling: ['/Users/iali/Stan/cmdstanpy/test/data/logistic', 'id=1', "
  "'random', 'seed=39631', 'data', "
  "'file=/Users/iali/Stan/cmdstanpy/test/data/logistic.data.R', 'output', "
  "'file=/var/folders/d4/lw2hd5xd3jncsdblcm5mjbdsmkgh_1/T/tmpth750rbk/logistic-202009221352-1-o_u7dqof.csv', "
  "'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']"),
 ('cmdstanpy', 'INFO', 'start chain 2'),
 ('cmdstanpy', 'DEBUG', 'threads: 5'),
 ('cmdstanpy',
  'DEBUG',
  "sampling: ['/Users/iali/Stan/cmdstanpy/test/data/logistic', 'id=2', "
  "'random', 'seed=39631', 'data', "
  "'file=/Users/iali/Stan/cmdstanpy/test/data/logistic.data.R', 'output', "
  "'file=/var/folders/d4/lw2hd5xd3jncsdblcm5mjbdsmkgh_1/T/tmpth750rbk/logistic-202009221352-2-7ewrl9hb.csv', "
  "'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']"),
 ('cmdstanpy', 'INFO', 'start chain 3'),
 ('cmdstanpy', 'DEBUG', 'threads: 5'),
 ('cmdstanpy',
  'DEBUG',
  "sampling: ['/Users/iali/Stan/cmdstanpy/test/data/logistic', 'id=3', "
  "'random', 'seed=39631', 'data', "
  "'file=/Users/iali/Stan/cmdstanpy/test/data/logistic.data.R', 'output', "
  "'file=/var/folders/d4/lw2hd5xd3jncsdblcm5mjbdsmkgh_1/T/tmpth750rbk/logistic-202009221352-3-pfu2g6pd.csv', "
  "'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']"),
 ('cmdstanpy', 'INFO', 'start chain 4'),
 ('cmdstanpy', 'DEBUG', 'threads: 5'),
 ('cmdstanpy',
  'DEBUG',
  "sampling: ['/Users/iali/Stan/cmdstanpy/test/data/logistic', 'id=4', "
  "'random', 'seed=39631', 'data', "
  "'file=/Users/iali/Stan/cmdstanpy/test/data/logistic.data.R', 'output', "
  "'file=/var/folders/d4/lw2hd5xd3jncsdblcm5mjbdsmkgh_1/T/tmpth750rbk/logistic-202009221352-4-e56b_wq0.csv', "
  "'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']"),
 ('cmdstanpy', 'INFO', 'start chain 5'),
 ('cmdstanpy', 'DEBUG', 'threads: 5'),
 ('cmdstanpy',
  'DEBUG',
  "sampling: ['/Users/iali/Stan/cmdstanpy/test/data/logistic', 'id=5', "
  "'random', 'seed=39631', 'data', "
  "'file=/Users/iali/Stan/cmdstanpy/test/data/logistic.data.R', 'output', "
  "'file=/var/folders/d4/lw2hd5xd3jncsdblcm5mjbdsmkgh_1/T/tmpth750rbk/logistic-202009221352-5-8hgrc04f.csv', "
  "'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']"),
 ('cmdstanpy', 'INFO', 'start chain 6'),
 ('cmdstanpy', 'DEBUG', 'threads: 5'),
 ('cmdstanpy',
  'DEBUG',
  "sampling: ['/Users/iali/Stan/cmdstanpy/test/data/logistic', 'id=6', "
  "'random', 'seed=39631', 'data', "
  "'file=/Users/iali/Stan/cmdstanpy/test/data/logistic.data.R', 'output', "
  "'file=/var/folders/d4/lw2hd5xd3jncsdblcm5mjbdsmkgh_1/T/tmpth750rbk/logistic-202009221352-6-3kxpxvtu.csv', "
  "'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']"),
 ('cmdstanpy', 'INFO', 'start chain 7'),
 ('cmdstanpy', 'DEBUG', 'threads: 5'),
 ('cmdstanpy',
  'DEBUG',
  "sampling: ['/Users/iali/Stan/cmdstanpy/test/data/logistic', 'id=7', "
  "'random', 'seed=39631', 'data', "
  "'file=/Users/iali/Stan/cmdstanpy/test/data/logistic.data.R', 'output', "
  "'file=/var/folders/d4/lw2hd5xd3jncsdblcm5mjbdsmkgh_1/T/tmpth750rbk/logistic-202009221352-7-zy9spqkd.csv', "
  "'method=sample', 'algorithm=hmc', 'adapt', 'engaged=1']"),
 ('cmdstanpy', 'INFO', 'finish chain 5'),
 ('cmdstanpy', 'INFO', 'finish chain 6'),
 ('cmdstanpy', 'INFO', 'finish chain 2'),
 ('cmdstanpy', 'INFO', 'finish chain 3'),
 ('cmdstanpy', 'INFO', 'finish chain 1'),
 ('cmdstanpy', 'INFO', 'finish chain 7'),
 ('cmdstanpy', 'INFO', 'finish chain 4'))
```

**Comment by mitzimorris** [comment]
the logic in the test doesn't anticipate a machine with more than 7 cores.
how many cores on your machine?

**Comment by imadmali** [comment]
6 physical (12 logical) cores.

**Comment by mitzimorris** [comment]
```
expected:
(('cmdstanpy', 'DEBUG', 'total threads: 60'),)
```

above msg is 12 logical cores * 5 - test is way too brittle.

**Pull request merged**
