### PR TITLE
Add documentation page on csv files and logging

### LINKED ISSUE #594: cmdstanpy_logger documentation
#### Summary:

@WardBrian clued me in on how to suppress logging output, which works:

```python
import logging
cmdstanpy_logger = logging.getLogger("cmdstanpy")
cmdstanpy_logger.disabled = True
```

But I don't see documentation anywhere on that.  A Google search for `[cmdstanpy_logger site:mc-tan.org]` yields nothing other than source code.

#### Current Version:

```python
>>> csp.cmdstan_version()
(2, 30)
```

I don't know how to get the cmdstanpy version itself, but the online doc says 1.04 and I just installed.

### PR DESCRIPTION
**Pull request by WardBrian**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and open-source license: see below

#### Summary

Closes #594. This adds a new page to the doc called "Controlling Outputs". I moved a lot of the CSV file specific stuff there from the Hello World page and added a section explaining the `logging` module vis-a-vis cmdstanpy

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):
Simons Foundation

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by WardBrian** [comment]
@mitzimorris this is the logging doc I mentioned yesterday. I don't specifically mention the option you do of setting the logging setting to WARNING, though - should I?

**Review by mitzimorris — APPROVED** [review]
thanks - this is a great re-org and addition

**Comment by mitzimorris** [comment]
reviewed and then saw comment - regarding logging setting, it's a mess.
perhaps things that we consider INFO are more properly DEBUG?
at the WARNING level you get the stanc compiler messages, but you also get warnings from the sampler that may or may not be real.

**Comment by WardBrian** [comment]
I think the things we currently have at INFO are pretty good. Moving them to DEBUG would mean a user couldn't see messages like "Sampling started" without getting all the other debug spam. We could set our logger to WARNING by default though.

**Comment by mitzimorris** [comment]
is there a way to catalogue the set of logging messages throughout the code?
perhaps a follow-on issue here would be to add a guide to logging outputs.

**Comment by WardBrian** [comment]
`grep -r "info(" cmdstanpy/` works pretty well for finding the logging at least, similar for `warning(` and `debug(`. Agree it would be good to review + document the usages of each.

**Pull request merged**
