### PR TITLE
Bugfix/455 csv single row

### PR DESCRIPTION
**Pull request by mitzimorris**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and open-source license: see below

#### Summary

Adds more unit tests to bugfix from ahartikainen:bugfix/shape_issues;  also fixes bug in CmdStanGQ - method `stan_variable` fails to properly reshape container vars.

Swapped out test model `test/data/shape.stan` with model `test/data/matrix_var.stan` which is bernoulli model with data supplied via transformed data, and generated quantities block which creates 4 x 3 matrix `z` where i,j entry == row_num.

Unit tests check that for all methods, `z` has both correct shape and correct values.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):  Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Review by ahartikainen — APPROVED** [review]
LGTM

**Comment by WardBrian** [comment]
More of an aesthetic comment than anything, but I don't think the name `test_bug_455` is particularly helpful. Could we call it something like `test_single_row_csv_reshaping`? A mouthful, but doesn't require you to open a browser or try to reverse engineer the bug to figure out what it is testing.

Other than that, LGTM

**Review by WardBrian — APPROVED** [review]
Good to merge once tests past

**Comment by dharris10-chwy** [comment]
Thanks again everyone!

**Pull request merged**
