### PR TITLE
Update workflow to allow manual runs on different CmdStan versions

### PR DESCRIPTION
**Pull request by WardBrian**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and open-source license: see below

#### Summary

This edits our main workflow to allow you to run it manually and specify a cmdstan version. Hopefully it is useful for things like https://github.com/stan-dev/cmdstan/issues/1061

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):
Simons Foundation

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Review by serban-nicusor-toptal — APPROVED** [review]
LGTM

**Review by ahartikainen — COMMENTED** [review]
What is the point on this change?

Is there a way to manually run GH workflow? Locally/Cloud?

**Comment by WardBrian** [comment]
You will be able run this by going to the `Actions` tab on the repo (like how we currently run the Release action). The main motivation is to be able to run the cmdstanpy tests on CmdStan release candidates as part of the release testing cycle

**Comment by rok-cesnovar** [comment]
> Is there a way to manually run GH workflow?

Yeah, similar to how its done for release CmdStanPy:

image

**Pull request merged**
