### PR TITLE
prevent path duplicate

### PR DESCRIPTION
**Pull request by guihigashi**
#### Submission Checklist

- [ ] Run unit tests
- [ ] Declare copyright holder and open-source license: see below

#### Summary

Same as #164, but in another place...

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Guilherme Higashi

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by guihigashi** [comment]
according to this [https://stackoverflow.com/questions/5629023/the-order-of-keys-in-dictionaries](url), OrderedDict guarantees keys order for python >= 2.7

**Comment by ahartikainen** [comment]
I don't remember, but I think we only support python 3.6+

**Comment by guihigashi** [comment]
I see. Still, for python 3.6 dict _"The order-preserving aspect of this new implementation is considered an implementation detail and should not be relied upon..."_ [What’s New In Python 3.6](https://docs.python.org/3.6/whatsnew/3.6.html#new-dict-implementation)

**Comment by ahartikainen** [comment]
use of `OrderedDict` is fine by me.

**Comment by mitzimorris** [comment]
@guihigashi please fill out copyright - assign to yourself if you'd like, or your uni

**Comment by guihigashi** [comment]
@mitzimorris Do I just edit the first comment and write my name (or github username)?

**Comment by mitzimorris** [comment]
@guihigashi - all good - once merge conflict is resolved, we're good to go.

**Comment by guihigashi** [comment]
I think it's ok now. Sorry for the mess, the typo on last commit message...
It seems appveyor got a network error "Cannot connect to github. HTTP Error 403: Forbidden"

**Pull request merged**
