### PR TITLE
Feature/141 better error messages

### PR DESCRIPTION
**Pull request by mitzimorris**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and open-source license: see below

#### Summary

Fix for issues #141 and #199.

Now the `RunSet` object stores CmdStan outputs to stdout and stderr in separate files.
If any CmdStan run returns a non-zero error code, the CmdStanPy methods report both the error code together with error messages.

The `RunSet` method `_get_err_msgs` parses lines beginning with `Exception` from the stdout file and gets the entire contents of stderr file, if any - this is needed because different errors are written to different output streams.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):  Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by mitzimorris** [comment]
hi, pinging @ahartikainen or @wesbarnett - do you have any cycles to review this?

**Comment by mitzimorris** [comment]
failing because of problems with latest ujson on appveyor?

```
Collecting ujson
266  Downloading ujson-2.0.0.tar.gz (7.1 MB)
...
Failed to build ujson
334ERROR: Could not build wheels for ujson which use PEP 517 and cannot be installed directly
```

**Comment by hugovk** [comment]
Hi, PR https://github.com/ultrajson/ultrajson/pull/370 is a likely fix for https://github.com/ultrajson/ultrajson/issues/369 with UltraJSON 2.0.0, and hopefully we'll get that released as 2.0.1 tomorrow.

In the meantime, you could pin to `ujson!=2.0.0`.

**Comment by mitzimorris** [comment]
pinned to `ujson==1.35`

**Comment by hugovk** [comment]
🚀 Fixed in UltraJSON 2.0.1:
* https://github.com/ultrajson/ultrajson/releases/tag/2.0.1
* https://pypi.org/project/ujson/2.0.1/

**Pull request merged**
