### PR TITLE
Enable install_cmdstan from python

### PR DESCRIPTION
**Pull request by ahartikainen**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and open-source license: see below

#### Summary

Copy `bin/install_cmdstan` to `cmdstanpy/install_cmdstan.py`
Also added a function that calls it with subprocess. `install_cmdstan`

This enables one to call in python (this call wrapping function)

    from cmdstanpy import install_cmdstan
    install_cmdstan(dir=None, version=None) # kw defaults to None

or from terminal (this call the install_cmdstan.py file)

    python -m cmdstanpy.install_cmdstan
    # python -m cmdstanpy.install_cmdstan --version 2.20.0

This is good, because by default `Script` folder is not available in Windows.

Added test that makes sure install_cmdstan files are equal. If bin/install_cmdstan file is not found, test is ignored.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Ari Hartikainen

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by ahartikainen** [comment]
Maybe there could be some `setup.py` magic, which could also work. I need to investigate (I don't like this duplicate code either)

**Comment by mitzimorris** [comment]
@ahartikainen instead of making this a script, use this instead?
https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html#the-console-scripts-entry-point

**Comment by ahartikainen** [comment]
Perfect, I will try this.

**Comment by ahartikainen** [comment]
This is now ready.

**Comment by mitzimorris** [comment]
need same fix for travis as appveyor

**Pull request merged**
