### PR TITLE
Add iPyKernel to doc build

### PR DESCRIPTION
**Pull request by WardBrian**
I think this resolves the second error I'm now getting

### CODE REVIEW

**Comment by serban-nicusor-toptal** [comment]
Hey, please give me a moment to give it a go inside a docker container to make sure this is it. Thanks!

**Comment by WardBrian** [comment]
I'd appreciate it - I'm not able to test the non-conda version locally so I'm sort of trying to ad-hoc adapt it

**Comment by serban-nicusor-toptal** [comment]
Ran it inside `python:3.9` and it seems to be fine, needed only `sudo apt-get install pandoc -y`.


<details>
  <summary>Build log</summary>
root@29e984185a5c:/tmp/cmdstanpy/docsrc# make github
make[1]: Entering directory '/tmp/cmdstanpy/docsrc'
Running Sphinx v4.1.2
python exec: /usr/local/bin/python
sys.path: ['/usr/local/bin', '/usr/local/lib/python39.zip', '/usr/local/lib/python3.9', '/usr/local/lib/python3.9/lib-dynload', '/usr/local/lib/python3.9/site-packages', '/tmp/cmdstanpy']
environment: environ({'HOSTNAME': '29e984185a5c', 'PYTHON_PIP_VERSION': '21.2.4', 'SHLVL': '1', 'OLDPWD': '/tmp/cmdstanpy', 'HOME': '/root', 'GPG_KEY': 'E3FF2839C048B25C084DEBE9B26995E310250568', 'MAKEFLAGS': 'w', 'MAKE_TERMERR': '/dev/pts/0', '_': '/usr/bin/make', 'PYTHON_GET_PIP_URL': 'https://github.com/pypa
/get-pip/raw/c20b0cfd643cd4a19246ccf204e2997af70f6b21/public/get-pip.py', 'TERM': 'xterm', 'PATH': '/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'MAKELEVEL': '2', 'LANG': 'C.UTF-8', 'PYTHON_VERSION': '3.9.6', 'MAKE_TERMOUT': '/dev/pts/0', 'PWD': '/tmp/cmdstanpy/docsrc', 'PYTHON_
GET_PIP_SHA256': 'fa6f3fb93cce234cd4e8dd2beb54a51ab9c247653b52855a48dd44e6b21ff28b', 'MFLAGS': '-w', 'DOCUTILSCONFIG': '/tmp/cmdstanpy/docsrc/docutils.conf'})
pip environment:
Package                       Version   Location
----------------------------- --------- --------------
alabaster                     0.7.12
attrs                         21.2.0
Babel                         2.9.1
backcall                      0.2.0
beautifulsoup4                4.9.3
bleach                        4.0.0
certifi                       2021.5.30
cffi                          1.14.6
charset-normalizer            2.0.4
cmdstanpy                     0.9.76    /tmp/cmdstanpy
codecov                       2.1.12
colorama                      0.4.4
coverage                      5.5
cryptography                  3.4.7
cycler                        0.10.0
debugpy                       1.4.1
decorator                     5.0.9
defusedxml                    0.7.1
docutils                      0.16
entrypoints                   0.3
idna                          3.2
imagesize                     1.2.0
importlib-metadata            4.6.4
ipykernel                     6.2.0
ipython                       7.26.0
ipython-genutils              0.2.0
jedi                          0.18.0
jeepney                       0.7.1
Jinja2                        3.0.1
jsonschema                    3.2.0
jupyter-client                6.1.12
jupyter-core                  4.7.1
jupyterlab-pygments           0.1.2
keyring                       23.1.0
kiwisolver                    1.3.1
MarkupSafe                    2.0.1
matplotlib                    3.4.3
matplotlib-inline             0.1.2
mistune                       0.8.4
nbclient                      0.5.4
nbconvert                     6.1.0
nbformat                      5.1.3
nbsphinx                      0.8.7
nest-asyncio                  1.5.1
numpy                         1.21.2
packaging                     21.0
pandas                        1.3.2
pandoc                        1.1.0
pandocfilters                 1.4.3
parso                         0.8.2
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        8.3.1
pip                           21.2.4
pkginfo                       1.7.1
plumbum                       1.7.0
ply                           3.11
prompt-toolkit                3.0.19
ptyprocess                    0.7.0
pycparser                     2.20
pydata-sphinx-theme           0.6.3
Pygments                      2.10.0
pyparsing                     2.4.7
pyrsistent                    0.18.0
python-dateutil               2.8.2
pytz                          2021.1
pyzmq                         22.2.1
readme-renderer               29.0
requests                      2.26.0
requests-toolbelt             0.9.1
rfc3986                       1.5.0
SecretStorage                 3.3.1
setuptools                    57.4.0
six                           1.16.0
snowballstemmer               2.1.0
soupsieve                     2.2.1
Sphinx                        4.1.2
sphinx-copybutton             0.4.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
testpath                      0.5.0
tornado                       6.1
tqdm                          4.62.1
traitlets                     5.0.5
twine                         3.4.2
ujson                         4.1.0
urllib3                       1.26.6
wcwidth                       0.2.5
webencodings                  0.5.1
wheel                         0.37.0
zipp                          3.5.0
[autosummary] generating autosummary for: api.rst, examples.rst, examples/MCMC Sampling.ipynb, examples/Maximum Likelihood Estimation.ipynb, examples/Run Generated Quantities.ipynb, examples/Variational Inference.ipynb, hello_world.rst, index.rst, installation.rst, overview.rst, workflow.rst
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://docs.scipy.org/doc/numpy/objects.inv...
loading intersphinx inventory from https://pandas.pydata.org/pandas-docs/stable/objects.inv...
loading intersphinx inventory from https://xarray.pydata.org/en/stable/objects.inv...
intersphinx inventory has moved: https://docs.scipy.org/doc/numpy/objects.inv -> https://numpy.org/doc/stable/objects.inv
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 11 source files that are out of date
updating environment: [new config] 11 added, 0 changed, 0 removed
INFO:cmdstanpy:found newer exe file, not recompiling
INFO:cmdstanpy:compiled model file: /root/.cmdstan/cmdstan-2.27.0/examples/bernoulli/bernoulli
INFO:cmdstanpy:start chain 1
INFO:cmdstanpy:start chain 2
INFO:cmdstanpy:start chain 3
INFO:cmdstanpy:start chain 4
INFO:cmdstanpy:finish chain 1
INFO:cmdstanpy:finish chain 2
INFO:cmdstanpy:finish chain 4
INFO:cmdstanpy:finish chain 3
WARNING:cmdstanpy:Keyword "name" is deprecated, use "var" instead.
INFO:cmdstanpy:Processing csv files: /tmp/tmpk3r9wyx9/bernoulli-202108171945-1-r5btspm0.csv, /tmp/tmpk3r9wyx9/bernoulli-202108171945-2-plw70hpc.csv, /tmp/tmpk3r9wyx9/bernoulli-202108171945-3-qi14zfpv.csv, /tmp/tmpk3r9wyx9/bernoulli-202108171945-4-fxas8wci.csv

Checking sampler transitions treedepth.
Treedepth satisfactory for all transitions.

Checking sampler transitions for divergences.
No divergent transitions found.

Checking E-BFMI - sampler transitions HMC potential energy.
E-BFMI satisfactory.

Effective sample size satisfactory.

Split R-hat values satisfactory all parameters.

Processing complete, no problems detected.
reading sources... [100%] workflow
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] workflow
generating indices... genindex py-modindex done
copying notebooks ... [100%] examples/Variational Inference.ipynb
highlighting module code... [100%] cmdstanpy.utils
writing additional pages... search done
copying images... [100%] _build/doctrees/nbsphinx/examples_MCMC_Sampling_18_1.png
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded.

The HTML pages are in _build/html.
deleting tmpfiles dir: /tmp/tmpk3r9wyx9
done
make[1]: Leaving directory '/tmp/cmdstanpy/docsrc'

</details>

**Review by serban-nicusor-toptal — APPROVED** [review]

**Comment by serban-nicusor-toptal** [comment]
This one is on me, give me a sec.

**Pull request merged**
