### PR TITLE
Enable TBB on Windows

### PR DESCRIPTION
**Pull request by ahartikainen**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and open-source license: see below

#### Summary

Add libTBB to $PATH on Windows and fix the env variable handling for subprocess.
Changes the default `make` to `mingw32-make` on Windows.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Ari Hartikainen

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by ahartikainen** [comment]
Is our tests running with cached `.exe` files?

**Comment by mitzimorris** [comment]
>  Is our tests running with cached .exe files?

I have written a script I use to clean out files created by running the unit tests - should we add this?  it's a cut-and-paste hack at the moment - it could be improved...

```
#!/bin/sh

if [[ -e cmdstanpy/__pycache__ ]]; then
  echo "remove cmdstanpy/__pycache__ dir"
  rm -rf cmdstanpy/__pycache__
fi

if [[ -e test/__pycache__ ]]; then
  echo "remove test/__pycache__ dir"
  rm -rf test/__pycache__
fi

if [[ -e docs/_build ]]; then
  echo "remove docs/_build dir"
  rm -rf docs/_build
fi

echo "remove compiled stan programs"
find test/data -perm 755 -and -type f
find test/data -perm 755 -and -type f -exec rm {} \;
find docs/notebooks -perm 755 -and -type f
find docs/notebooks -perm 755 -and -type f -exec rm {} \;

echo "remove stan program .hpp files"
find test/data -name "*.hpp"
find test/data -name "*.hpp" -exec rm {} \;
find docs/notebooks -name "*.hpp"
find docs/notebooks -name "*.hpp" -exec rm {} \;

echo "remove stan program .o files"
find test/data -name  "*.o"
find test/data -name  "*.o" -exec rm {} \;
find docs/notebooks -name  "*.o"
find docs/notebooks -name  "*.o" -exec rm {} \;
```

**Comment by ahartikainen** [comment]
I did a simple python function, so it works on Windows too.

I'm not even sure if this is true or not.

Somehow it is just bizarre that tests are passed on Windows with CmdStan 2.21 without this fix. (But this fix is needed on my local machine with CmdStan 2.21).

**Comment by ahartikainen** [comment]
Oh, And travis / appveyor installs cmdstanpy from scratch, so only CmdStan and RTools are cached.

**Comment by ahartikainen** [comment]
There are more fixes to `install_cxx_toolchain`, but I will make these in different PR. Mainly the way users would need to use the library and let's see if we can also see if there is a way to see other RTools install locations.

**Comment by mitzimorris** [comment]
> Somehow it is just bizarre that tests are passed on Windows with CmdStan 2.21 without this fix. (But this fix is needed on my local machine with CmdStan 2.21).

what is your local machine?  different environments?  paths?

**Pull request merged**
