### PR TITLE
[WIP] update jsondump and rdump

### PR DESCRIPTION
**Pull request by ahartikainen**
#### Submission Checklist

- [ ] Run unit tests
- [x] Declare copyright holder and open-source license: see below

#### Summary

Enable size 0 and 1 arrays.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Ari Hartikainen

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by ahartikainen** [comment]
I think there are two different bugs

size 1 real/int array/vector vs real/int
Empty arrays as data. Can CmdStan have them?

**Comment by ahartikainen** [comment]
There is something weird going on with PR (deleted functions etc), so I need to figure that one out.

@mitzimorris do you know what should be the correct way to handle these

data array/vector with size 0
data array/vector with size 1

Can cmdstanpy currently handle these? From both interfaces JSON/RDump?

ps. Also if you want you can update this functionality to the current bigger PR, and I can then close this one

**Comment by mitzimorris** [comment]
> data array/vector with size 0

CmdStan allows empty arrays (although couldn't make this happen using RStan).

however, the current JSON parser as implemented doesn't allow them - mea culpa -
I implemented an ad-hoc JSON parser back in 2014 because we couldn't find a C++ JSON parsing library that had implemented a SAX parser.  now there is one and there's a CmdStan issue on using this parser that I need to take care of ASAP.

> data array/vector with size 1

CmdStan has no problem with these.

here's the model - "test_inputs.stan":

```
data {
  int<lower=0> N;
  int<lower=0> y[N];
  vector<lower=0,upper=1>[N] x;
}
transformed data {
  print(N);
  print(y);
  print(x);
}
```

data file "test_zero_vecs.data.R":

```
N <- 0
y <- c()
x <- c()
```

data file "test_zero_vecs.data.json":
```
{
    "N" : 0,
    "y" : [],
    "x" : [],
}
```

**Comment by ahartikainen** [comment]
Yeah, currently we can't have 0-sized array for CmdStan --> Let's not allow them now --> Let's raise an error if user tries to use one. (Or we can just let CmdStan fail, and after fix, it will work)

I updated the behavior for the 1-sized arrays. There was an off-by-one error with length handling.

I test against Sequence --> list, tuple and some other special formats -> json transform them to `[...]` and for RDump I call `np.asarray` for ndarray and sequence --> all are transformed to numpy array (unless they are already).

**Comment by mitzimorris** [comment]
> Yeah, currently we can't have 0-sized array for CmdStan --> Let's not allow them now 

if we do this, we need to
a) test that Rdump files created by CmdStanPy's utility function 'rdump' work for 0-length arrays etc
b) change the behavoir of 'MaybeDictToFilePath' to generate rdump files instead of json files.

this should avoid the problem unless the user calls  `jsondump` directly.

in addition, we need to file an issue so that once the fix is in CmdStan and the next CmdStan release is out (scheduled for October), we update CmdStanPy so that everything works as it should.

**Pull request merged**
