### PR TITLE
Fix/354

### PR DESCRIPTION
**Pull request by NourFahmy**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and open-source license: see below

#### Summary
Worked with @bbbales2  to solve [this issue](https://github.com/stan-dev/cmdstanpy/issues/354)
#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by bbbales2** [comment]
@mitzimorris what sorta tests would make sense for this one? Looks like right now the optimize test is just a single does-it-work-kinda-test.

Should we test each argument individually?

Also is there a way to run an autoformatter on the code to fix the lint errors?

**Comment by ahartikainen** [comment]
Hi, please update copyright part (add your name)

In the git folder do the following to autoformat.

    python -m black cmdstanpy

Is there are way to check that given argument is also seen in the CmdStan side? (parsing the csv?)

**Comment by mitzimorris** [comment]
> Is there are way to check that given argument is also seen in the CmdStan side? (parsing the csv?)

yes, you could do this because the CSV parsing routines return a dict which contains the set of specified args, critically, not default arg values - https://github.com/stan-dev/cmdstanpy/blob/09d2c6c6a8c544fba7001517a62b90cd1ced04fd/cmdstanpy/utils.py#L582
 
what you'd want to do is run optimization, then check the csv file, as in this test:
https://github.com/stan-dev/cmdstanpy/blob/09d2c6c6a8c544fba7001517a62b90cd1ced04fd/test/test_utils.py#L271

**Comment by mitzimorris** [comment]
and many thanks for fixing this one! 

we didn't go with the policy of exposing all possible CmdStan args to all methods, because on the sampler side, we didn't want to expose static HMC because that's a special thing and not generally useful.

therefore, when the `optimize` method went in, it seemed OK to not expose everything - obviously, we missed a few things.

**Comment by NourFahmy** [comment]
Hi @mitzimorris - I wanted to clarify how thorough the unit tests would need to be:
1) can we have one 'good' test with appropriate values for the new kwargs?
2) and can we have one 'bad' test with kwarg values that aren't viable?
what is typically best practice?

**Comment by mitzimorris** [comment]
yes, one good, one bad test is great.
examples here- https://github.com/stan-dev/cmdstanpy/blob/09d2c6c6a8c544fba7001517a62b90cd1ced04fd/test/test_sample.py#L498

**Comment by mitzimorris** [comment]
hi @NourFahmy - is this ready for review?

**Comment by NourFahmy** [comment]
Hi @mitzimorris - not yet! I have some time scheduled for friday morning to get the test cases for 'bad' arguments, and take care of the code coverage decrease.

**Comment by mitzimorris** [comment]
hi @NourFahmy, happy to finish this off if you're swamped with other stuff.

**Comment by NourFahmy** [comment]
Hi @mitzimorris - I hope you're well! Do you mind picking it up? I think it just needs linting - in the future, would I need to run python -m black?

**Review by mitzimorris — APPROVED** [review]
LGTM! many thanks for doing this!

**Pull request merged**
