### PR TITLE
Automatically set number of used cores

### PR DESCRIPTION
**Pull request by wsuchy**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and open-source license: see below

#### Summary
Instead of having number of cores set to 1 by default, let's set it to the number of chains with the limitation of `cpu_count - 2` (to leave some cores for the OS).

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

- Salesforce

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by maedoc** [comment]
How is cpu count being computed? If this returns the number of hyperthreads, then performance suffers à lot when Stan chains overlap on the same physical core.

**Comment by mitzimorris** [comment]
I don't see any problem with doing things this way.  I don't think we need to enforce uniform behavoir across the interfaces down to this level.  any thoughts from @jgabry or @ahartikainen ?

**Comment by wsuchy** [comment]
@maedoc  yes it does give you number of HT, yet my assumption is that on modern machines number of chains will usually be smaller (x2) than number of total HT cores. Example: for 4 chains and 12 HT cores (6 real) you will get still full performance. I am not sure if there is an easy way of getting number of real cpus that would work on Mac, Linux and Windows.

**Comment by mitzimorris** [comment]
> my assumption is that on modern machines number of chains will usually be smaller (x2) than number of total HT cores

we need to plan for a wide range of potential users. 
is this an issue for a 'non-modern' machine?  old-school cluster?

**Comment by maedoc** [comment]
Anyone running Stan likely has 2 cores or more, but I would strive to avoid more chains than physical cores as resource contention makes it too slow (except on Xeon Phi...)

**Comment by wsuchy** [comment]
@mitzimorris It will not impact old machines, we are actually interested in achieving to performance for modern MacBook etc where you have e.g 6 physical cores by 12 logical due to the hyper threading.
@maedoc I tested it with prophet model and got the result (MacBookPro, 6 cores, 12 HT):
12 chains, 12 cores: TIME: 242.229299359
12 chains 6 cores: TIME: 286.67894008400003
It turns out to be the opposite, the HT improved the performance by ~ 15.5%

**Comment by maedoc** [comment]
That's not the general trend I've seen across the hardware I've benchmarked, but it could be differences in model as well, especially if yours sit nicely in L3 cache.

**Comment by wsuchy** [comment]
@maedoc as we are talking about the default value here (that users can change) do you think we could close the loop now and merge it, or perhaps more investigation is needed?

**Comment by mitzimorris** [comment]
> 12 chains, 12 cores: TIME: 242.229299359

with this PR, you would get 10 chains for 12 cores, correct?
what do the times look like for that?

**Comment by mitzimorris** [comment]
> psutil.cpu_count(logical=False)
> that would require us to use another library @mitzimorris if that ok to have it as another dependency?

are there other features that could benefit from psutil?  e.g. issues #46 or #48 ?

**Comment by wsuchy** [comment]
With 12 chains and 10 cores the result is  308.07261098000004 (note that I intentionally left some resources for the OS). I am not sure if the library would solve any of the issues out-of-the-box. Actually both issues could be easily solved if CmdStan implemented a way of talking to it via TCP but that's a different story.

**Comment by mitzimorris** [comment]
so no to adding dependency on psutil.
agreed that since this only affects default behavior it's OK.

**Pull request merged**
