### PR TITLE
Feature/88 go faster

### PR DESCRIPTION
**Pull request by mitzimorris**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and open-source license: see below

#### Summary

Tightened up code which reads in stan csv files.  Added unit test that can be used to compare runtimes.

Conclusion is that underlying problem is lack of binary file format for output files.   Timing tests show that CmdStan and CmdStanPy have about the same runtime to run one chain of the sampler on a non-trivial model (2000 parameters, 1000 sampling iterations).

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):  Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by ahartikainen** [comment]
How much faster is this?

**Comment by mitzimorris** [comment]
trivially faster.

**Comment by mitzimorris** [comment]
in CmdStanPy, for the `sample` method, the set of stan-csv files are read twice - first by `_validate_csv_files`, then `_assemble_sample`

`_validate_csv_files` does the following:

-  parses the initial comments to get the sampler config, 
- parses out the column header,
- skips the warmup draws, if any
- parses the metric out of comment lines, (as needed)
- checks the output draws to make sure that the sample has the correct shape - i.e. number of draws and columns.

`_assemble_sample` gets the output draws and does the conversion from ascii to float.

for a sample of 1000 draws over 2000 parameters, changes here only sped things up by milliseconds -  the processing time in `_assemble_sample`  - multiple runs showed a consistent speedup, but not by much - on my machine things went from 1.4 sec to 1.3 seconds -

```
for x in {1..10}; do python -m unittest test.test_sample.StanMCMCTest.test_assemble_sample_big; done
```

OTOH, this does clean up one corner of the code.

**Comment by rok-cesnovar** [comment]
What is the largest hurdle with adding a binary format for output in cmdstan? I would be interested in adding that to cmdstan. I guess this would help both cmdstanpy and cmdstanr. Is it the lack of consensus on the exact format? Would httpstan's [writer proto](https://github.com/stan-dev/httpstan/blob/master/protos/callbacks_writer.proto) be a good start?

**Comment by mitzimorris** [comment]
I would love to see binary format for output in cmdstan.

**Comment by mitzimorris** [comment]
closing for now, we can revisit later.

**Pull request closed without merging**
