### PR TITLE
Explicitly declare public API

### LINKED ISSUE #176: Set __all__ in __init__.py
#### Summary:

Good morning! I think `__all__` should be set in `__init__.py`

#### Description:

I realize the following is not usually considered good practice, but if someone imports as follows it imports everything not prefixed with an underscore:

```
>>>from cmdstanpy import *
>>> dir()
['CmdStanGQ', 'CmdStanMCMC', 'CmdStanMLE', 'CmdStanModel', 'CmdStanVB', 
'STANSUMMARY_STATS', 'TMPDIR', '__annotations__', '__builtins__', '__doc__', '__loader__', 
'__name__', '__package__', '__spec__', 'atexit', 'cleanup_tmpdir', 'cmdstan_args', 'cmdstan_path',
'install_cmdstan', 'model', 'set_cmdstan_path', 'set_make_env', 'shutil', 'stanfit', 'tempfile', 'utils']
```

To solve this either `__all__` can be set explicitly to those items that the project wants exported for the "public API".

For example, it could be set as:

```
__all__ = ['set_cmdstan_path', 'cmdstan_path', 'set_make_env',
            'install_cmdstan', 'set_cmdstan_path', 'CmdStanMLE', 'CmdStanGQ',
            'CmdStanVB', 'CmdStanModel' ]
```

Alternatively it could be set to an empty list indicating the module is not designed for this type of import statement:

```
__all__ = []
```

In this case the module can still be imported as usual with:

```
import cmdstanpy
```

or one can indicate what to import explicitly:

```
from cmdstanpy import cmdstan_path
```

Here is the [PEP8 reference](https://www.python.org/dev/peps/pep-0008/#public-and-internal-interfaces).

#### Current Version:

master branch (0.6.0)

### PR DESCRIPTION
**Pull request by wesbarnett**
Fixes #176.

#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and open-source license: see below

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): American Express

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by wesbarnett** [comment]
I tested with cmdstan 2.21 on my local machine.

**Comment by wesbarnett** [comment]
I tested with cmdstan 2.21 on my local machine.

**Comment by wesbarnett** [comment]
I'm not sure how to retrigger the tests.

**Comment by ahartikainen** [comment]
I restarted the CI. I think you would need permission on travis / appveyor to see the restart button

**Comment by wesbarnett** [comment]
Thanks! This PR additionally improves `help(cmdstanpy)` since that uses the public API to populate the help. See my comments in bug #176 on what it looked like before.

**Pull request merged**
