### PR TITLE
Proposal: Update docs theme

### PR DESCRIPTION
**Pull request by WardBrian**
#### Submission Checklist

- [x] Declare copyright holder and open-source license: see below

#### Summary
This switches from the sphinx-readthedocs theme to[ pydata-sphinx-theme](https://pydata-sphinx-theme.readthedocs.io/en/latest/index.html) with some customizations. The idea is to look in-place next to the mc-stan.org website and especially the cmdstanr documentation, while still looking like a Python doc. The pydata theme is used by numpy, pandas, xarray, and others.

A preview page (which also features the changes of #432) can be seen here:  https://wardbrian.github.io/doc-preview/index.html

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):
Simons Foundation

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by WardBrian** [comment]
I should also note that this is done with the default css besides making the navbar dark. We can change anything we'd like - numpy changes all the header (h1, h2, etc) colors, which I think is a good idea to make them stand out.

**Comment by mitzimorris** [comment]
this looks great!

**Comment by WardBrian** [comment]
Since #432 has been merged, this is ready for comments/to go if we want it.

**Review by ahartikainen — APPROVED** [review]

**Comment by mitzimorris** [comment]
building locally - got this

> WARNING: html_static_path entry '_static' does not exist
> WARNING: logo file '_static/images/logo_icon.png' does not exist
>

**Comment by mitzimorris** [comment]
why is  red P mark visible?

**Comment by WardBrian** [comment]
Good catch. Fixing now, the png didn't get added to the commit 

The P mark is so you can click it to make a link to a specific part of the page, like:
https://numpy.org/doc/stable/user/whatisnumpy.html#who-else-uses-numpy

I know you can change the color in CSS, not 100% sure about hiding it but should be possible if we want

**Comment by mitzimorris** [comment]
> It should also only be visible when you hover over it, if the javascript for the page is loaded.

always visible - color is: https://convertingcolors.com/rgb-color-198_15_15.html 
took a look at the css here: https://github.com/pydata/pydata-sphinx-theme/blob/master/pydata_sphinx_theme/static/css/theme.css
but not sure what we'd need to do to override.

I find the red rather distracting - (not a problem for the r/b colorblind, so that's good ;-) ).

**Comment by WardBrian** [comment]
Fixed the always visible issue. Still want a color change? 

If so, what color?

**Comment by mitzimorris** [comment]
thanks for fixing - no need to mess with colors!

**Pull request merged**
