### PR TITLE
Feature/63 advi

### PR DESCRIPTION
**Pull request by mitzimorris**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and open-source license: see below

#### Summary

Add method `variational` to class `Model` which runs CmdStan's variational inference algorithm.

Variational inference is like optimization in that it returns an estimate of the parameters and it is like sampling because it also returns a sample.  Like optimization, as designed, this method only runs one chain by default and the exposed estimate and sample are from chain 1.

The class `StanVariational` holds the returned estimate and sample.  Like class `StanMLE` it returns the estimated parameters either as a dict, a numpy ndarray, or a pandas dataframe.  Like class `StanFit` it also returns a sample.  The name used for variational parameter estimates is:  `variational_params_XXX` where XXX is either `dict`, `np`, `pd`, following the optimize pattern `optimized_params_XXX`.   Suggestions for a better name welcome!

This PR includes update to the docs and an ipython notebook which won't work until this feature is merged into master and uploaded to PyPi.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Columbia University

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by mitzimorris** [comment]
@maedoc - how are you using ADVI and would this implementation work for you?

**Comment by maedoc** [comment]
Yep this would work for us, we usually bump elbo/grad samples up a lot and play with eta.

unrelated but there are a bunch of non-advi changes in the diff here (e.g. validation, renaming etc), may be worth a rebase

**Comment by mitzimorris** [comment]
> unrelated but there are a bunch of non-advi changes in the diff here (e.g. validation, renaming etc), may be worth a rebase

rebase?  not sure - to be honest, I'm a bit scared of getting too fancy with Git.

my bad for adding unrelated validation checks - during testing I noticed that the type checks should be more stringent so I added them to the sampler args.

what do you mean by `renaming`? there's a 2nd PR open on how handle fixed_params - perhaps I should have branched this feature off of that branch - is there overlap in the changes I made?  if PR #119 goes in first, will this all work?

**Comment by mitzimorris** [comment]
@maedoc - if you have free cycles, please review this and/or PR #119 

at which point, CmdStanPy will expose as much of CmdStan as originally intended:

* the NUTS-HMC sampler
* optimization
* advi
* standalone generated quantities

is there any other part of CmdStan that you think should be exposed?

**Comment by maedoc** [comment]
> my bad for adding unrelated validation checks

Sorry, I just wanted to flag it in case it was an accident, which can happen when there are multiple PRs not using the same parent commit.  

> what do you mean by `renaming`?

In the diff I saw `StanFit` was then named `RunSet`, but I haven't followed the recent PRs enough to know which is correct.

> if PR #119 goes in first, will this all work?

Most likely but only Git knows.  you can try to locally merge it all and see where the conflicts are (the suggestion to rebase is just a way to make the commit history look nice but a merge commit accomplishes the same thing)

> is there any other part of CmdStan that you think should be exposed?

In my opinion, no, I think it's in very good shape now particularly how all the arguments are validated, is  a bit thankless yet important work (thanks!)

>  if you have free cycles, please review this and/or PR #119

done

**Comment by mitzimorris** [comment]
> In the diff I saw `StanFit` was then named `RunSet`, but I haven't followed the recent PRs enough to know which is correct.
> 

hi @maedoc,  this change happened in https://github.com/stan-dev/cmdstanpy/pull/117 - 
the issue filed for it was https://github.com/stan-dev/cmdstanpy/issues/112

I think that refactor brought CmdStanPy right back around to where PyCmdStan started  ;-)

**Pull request merged**
