### PR TITLE
Removed .png from .gitignore, make sure release adds all untracked fi…

### PR DESCRIPTION
**Pull request by serban-nicusor-toptal**
- Remove `*.png` from `.gitignore` as there are .png files in the docs directory.
- Stop using `git commit -m "" -a` and instead use `git add .` to add all tracked/untracked files.
- Remove `_sources` and `_modules` from /docs

#### Submission Checklist

- [ ] Run unit tests
- [ ] Declare copyright holder and open-source license: see below

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by mitzimorris** [comment]
when you move the docs from the `docsrc/_build` to `docs` you need to:
a) get rid of directories "_modules" and "_sources".
b) rename "_static" to "static"

based on this:

Untitled

**Comment by serban-nicusor-toptal** [comment]
Thank you @mitzimorris total life saver! me and @WardBrian were trying to figure it out

**Comment by mitzimorris** [comment]
nevermind - (underscore is OK - minor brain fart)

**Comment by WardBrian** [comment]
I think renaming _static will break things, we should revert that latest commit

**Comment by mitzimorris** [comment]
he's correct - the developer console was displaying the name with "_static" correctly - obscured by link underline.  my bad.

**Comment by WardBrian** [comment]
I think this will work now. Any idea why readthedocs hasn't built yet?

**Review by WardBrian — APPROVED** [review]

**Comment by serban-nicusor-toptal** [comment]
sadly with RTD we hit into a limit, need to wait 15 mins to 60 mins

**Comment by WardBrian** [comment]
It looks like a few of the old builds are still sitting around spinning, can we can those somehow to speed it up? e.g. https://readthedocs.org/projects/cmdstanpy/builds/14497521/

Hopefully we will never have to push more than one thing to them again and avoid this issue

**Comment by serban-nicusor-toptal** [comment]
Sadly I don't think so, there isn't any option to speed up, cancel or rebuild. I just hope it isn't completely stuck

**Comment by WardBrian** [comment]
Supposedly it is supposed to get killed if it takes more than 15 minutes, but who knows about that. I'm sure it will shake out eventually, we may need to manually prod it at some point though, and then just avoid overloading it in the future

**Comment by WardBrian** [comment]
Oh, when you reverted you didn't rename the folder, just change the command in make. The docs are still broken then, until that gets renamed or it gets re-run

**Comment by serban-nicusor-toptal** [comment]
Ah you're right, I need to re-ran it anyway so it gets fixed by CI: https://github.com/stan-dev/cmdstanpy/actions/runs/1141099103

**Comment by WardBrian** [comment]
huzzah, it has been fixed: https://mc-stan.org/cmdstanpy/. RTD is still spinning, but we had that working before so I trust it will sort out.

Thanks for all the troubleshooting @serban-nicusor-toptal

**Comment by serban-nicusor-toptal** [comment]
Glad it's sorted out, thanks everyone for the action and help on this! Have a great day/evening

**Comment by mitzimorris** [comment]
OK, I'm a moron - the _modules are what contains the source code - all the source links are broken.  damn.

**Comment by serban-nicusor-toptal** [comment]
No worries at all I'm still around. What about the other one, should it
still be removed? Gonna open a pr in a minute

**Comment by WardBrian** [comment]
I think it's safer to leave it

**Comment by WardBrian** [comment]
If you're gonna rebuild the docs again, can you add

```python
copybutton_prompt_text = r">>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: "
copybutton_prompt_is_regexp = True
```

to conf.py? I meant to add this, it makes the copying behavior on code examples cleaner by removing things like `In [10]:` from the text to be copied

**Comment by mitzimorris** [comment]
> No worries at all I'm still around. What about the other one, should it still be removed?

we need both `_modules` and `_sources`.

**Comment by serban-nicusor-toptal** [comment]
Kept both, can you please confirm it's working as expected?

**Comment by WardBrian** [comment]
It looks good to me

**Pull request merged**
