### PR TITLE
use Fortran order for utils.jsondumps

### PR DESCRIPTION
**Pull request by ahartikainen**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and open-source license: see below

#### Summary

Transform nD arrays with Fortran order

    np.array(...).T.tolist()

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Ari Hartikainen

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by ahartikainen** [comment]
We still need to test that this works correctly. (Fortran order) --> test for nD data

**Comment by ahartikainen** [comment]
Ready for review.

Do we need to checkout also json input or are we only reading symmetric data?

**Comment by ahartikainen** [comment]
This group

        if isinstance(val, np.ndarray):
            if val.size > 1:
                # .T for Fortran order
                data[key] = val.T.tolist()
            else:
                data[key] = []

should we remove empty keys or keep them as empty?

**Comment by mitzimorris** [comment]
what is the issue here?
does this change anything about the resulting .json file on disk?
my understanding is that in JSON, multi-dim arrays (lists of list) are written in row-major order (i.e., C-style) and the CmdStan is going to process the json file accordingly.

**Comment by ahartikainen** [comment]
Ok (which is great news), if that is true, then there is only the issue with empty array. Do we remove those parameters?

**Comment by mitzimorris** [comment]
good call - we should allow this.

**Comment by ahartikainen** [comment]
So we should update jsondump (other PR)

```
def jsondump(path: str, data: Dict) -> None:
    """Dump a dict of data to a JSON file."""
    empty_keys = []
    for key, val in data.items():
        if isinstance(val, np.ndarray):
            val = val.tolist()
            data[key] = val
        if (isinstance(val, (list, tuple)) and not val) or val is None:
            empty_keys.append(key)
    for key in empty_keys:
        del data[key]
    with open(path, 'w') as fd:
        json.dump(data, fd)
```

I will close this PR.

**Pull request closed without merging**
