### PR TITLE
Support json dumping for more collections

### PR DESCRIPTION
**Pull request by WardBrian**
e.g. pandas or other numpy wrappers

See #397 

#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and open-source license: see below

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Brian Ward, Flatiron Institute

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Review by mitzimorris — APPROVED** [review]
LGTM - many thanks!

**Comment by mitzimorris** [comment]
hi @WardBrian, see wiki, "Developers" section for details on PyLint and flake8.
we don't reformat automatically - I know the Stan C++ repos do this - should we?

**Comment by WardBrian** [comment]
It might be a good idea to include a .flake8 file and use something like [pre-commit](https://pre-commit.com/) to enforce those. I believe currently it is failing based on files I haven't touched, so this suggests to me that the main branch of the repo is not in a correct state

**Comment by WardBrian** [comment]
I've checked any the errors generated during my tests are also generated if you run flake8 and pylint on a fresh clone of develop. Some of the code it is complaining about has been in the package for over 2 years. I have been trying to puzzle out why this means all PRs aren't failing, but I frankly have no idea.

**Pull request merged**
