### PR TITLE
Prep for release v1.2.0

### PR DESCRIPTION
**Pull request by WardBrian**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and open-source license: see below

#### Summary

See #690. This is PR is assuming we go down the "issue as many warnings as possible for a version" branch before releasing a 2.0

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

Simons Foundation

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by WardBrian** [comment]
@mitzimorris I think we should try to do 1.2.0 early next week at this point

**Comment by WardBrian** [comment]
No, a new example notebook would be great

**Comment by WardBrian** [comment]
@mitzimorris do you have time to review this week? It would be great to release 1.2 with Pathfinder included

**Review by mitzimorris — APPROVED** [review]
LGTM!  thanks for the cleanup

**Pull request merged**
