### PR TITLE
Restore cwd after do_command error WIP

### PR DESCRIPTION
**Pull request by maedoc**
#### Submission Checklist

- [x] Run unit tests
- [x] Declare copyright holder and open-source license: see below

#### Summary

Addresses #506.

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): myself

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by maedoc** [comment]
It would be better if `pushd` was a proper context manager which handled exceptions by restoring cwd but this is easier and fixes the issue at hand.  The only other use of `pushd` is in the install cmdstan/toolchain functions.

**Comment by WardBrian** [comment]
You can use try/except blocks inside a [contextlib.contextmanager](https://docs.python.org/3/library/contextlib.html#contextlib.contextmanager) function like pushd. I think replacing the `yield` in pushd with

```python
try:
    yield
except Exception:
    raise
finally:
    os.chdir(previous_dir)
```

would resolve the issue and be much more general

We can also then test pushd directly:

```python
dir = os.getcwd()
with self.AssertRaises(RuntimeError):
    with pushd('data'):
        raise RuntimeError('testing')
self.assertPathsEqual(dir, os.getcwd())
```

**Comment by ahartikainen** [comment]
Yes I think adding

```python
try:
    yield
finally:
    os.chdir(previous_dir)
```

is needed

https://github.com/stan-dev/cmdstanpy/blob/5b80eb84ad1bf8fa093013d3b06a1c3594093092/cmdstanpy/utils.py#L1317

**Comment by WardBrian** [comment]
@maedoc Let me know if you'd prefer if myself or Ari take the PR from here in terms of changes. Thanks for finding this issue and jumping on it so quickly!

**Comment by maedoc** [comment]
All the test failures are trying to compile the model with CmdStan on macOS.  The error is the same as when I try to use a CmdStan build for x86_64 on Rosetta on macOS from Python running on arm64, or vice versa.  Perhaps the CI script needs to be updated to check arch and rebuild CmdStan accordingly.

**Comment by WardBrian** [comment]
I believe the error is because GitHub Actions updated the version of MacOs used but is caching old cmdstans. I’ll look into it

Thanks for the changes! I believe that with assertRaises there’s no need for a try/except in the test code. Other than that it looks great and I’ll merge once I fix the CI issues

**Comment by maedoc** [comment]
> I believe that with assertRaises there’s no need for a try/except in the test code.

Some static analysers don't know that `self.assertRaises` catches exceptions and see the subsequent code as unreachable.  Up to you..

**Comment by WardBrian** [comment]
We're not using try/except anywhere else in the tests where we use assertRaises, so for consistency I think don't here

**Comment by WardBrian** [comment]
The one test failure is from a timeout (I think we tried to download cmdstan too many times in short succession) so this is good to go

**Review by WardBrian — APPROVED** [review]

**Comment by WardBrian** [comment]
Thanks again @maedoc !

**Pull request merged**
