### PR TITLE
Update MCMC Sampling.ipynb

### PR DESCRIPTION
**Pull request by mjhajharia**
See #574 I've only changed the last cell and re-ran the notebook

### CODE REVIEW

**Comment by WardBrian** [comment]
The change is great, do you mind clearing the outputs of the notebook? The versions we check in are always blank, they get run during the docs build

**Comment by mjhajharia** [comment]
> The change is great, do you mind clearing the outputs of the notebook? The versions we check in are always blank, they get run during the docs build

you got it!

**Comment by mjhajharia** [comment]
> The result is different from the intended image (for some reason, the code works totally fine for me locally despite not building in the docs)
> 
> Current output: image
> 
> This PR:
> 
> image
> 
> I think we should use either `list(range(...` or `np.arange` to get the intended binning

which python version are you on?
`fit_sim.draws_pd()['theta_rep'].plot.hist(list(range(1,datagen_Data['N']+1)))` throws ValueError: Grouper for '0' not 1-dimensional for me

**Comment by mjhajharia** [comment]
and `y_sums = y_sims.sum(axis=1)` is doing nothing, its just converting the dataframe to a series, was DataFrame.cumsum meant to use here?

**Comment by WardBrian** [comment]
I believe you need to name the argument with `bins=0`, the first positional argument of `.plot.hist` is used for something different

**Comment by WardBrian** [comment]
Yeah, the original code is kind of messy. I believe that `sum(axis=1)` is functioning like a `squeeze()` - before hand the object has shape `(1000, 1)`, afterwards the shape is just `(1000, )`

**Comment by mjhajharia** [comment]
> I believe you need to name the argument with `bins=`, the first positional argument of `.plot.hist` is used for something different

that would mean 300 bins? i think @mitzimorris said we wanted 10?

**Comment by mjhajharia** [comment]
> Yeah, the original code is kind of messy. I believe that `sum(axis=1)` is functioning like a `squeeze()` - before hand the object has shape `(1000, 1)`, afterwards the shape is just `(1000, )`

yeah no i think it might be old code, currently the .plot.hist is i think a pandas wrapper for matplotlib so it can directly access dataframes. and we could just use by="theta_rep" instead of removing the columns.

**Comment by WardBrian** [comment]
We also have the ability to request only specific variables from `draws_pd`, so in the interest of both the cleanest code and displaying the greatest number of features I would have the cell be 

```python
fit_sim.draws_pd('theta_rep').plot.hist()
```

**Comment by mjhajharia** [comment]
> We also have the ability to request only specific variables from `draws_pd`, so in the interest of both the cleanest code and displaying the greatest number of features I would have the cell be
> 
> ```python
> fit_sim.draws_pd('theta_rep').plot.hist()
> ```

agreed, also i get where the code is coming from now -> https://cmdstanpy.readthedocs.io/en/stable-0.9.65/sample.html#example-generate-data-fixed-param-true check the end here,  this was pre- `draw_pd()` so they had to convert it to a dataframe. still makes no sense because axis=1 for an array????

**Comment by mjhajharia** [comment]
> Besides the code change, there's a bunch of extra metadata being added by this PR. Are you running these in Jupyter or something like VSCode/Pycharm? Do you have something like `nbstripout` installed to remove it? It's also possible to open in just a normal text editor and edit as json
> 
> I don't think there is necessarily any harm in it, but it would be nicer if it wasn't in the repo

yeah i'll do that no worries

**Comment by mitzimorris** [comment]
ignore my previous comment.  all I can say is whenI wrote this, I wasn't particularly fluent in Python and more stuff was added to API later which made this a whole lot easier.  whatever you do to clean this up would be great.

**Comment by mjhajharia** [comment]
> ignore my previous comment. all I can say is whenI wrote this, I wasn't particularly fluent in Python and more stuff was added to API later which made this a whole lot easier. whatever you do to clean this up would be great.

no worries, i think the issue is that the code in the .stan file has changed from the original code in 0.9, and the code in the notebook is the same, I'll try to get it working tonight

**Comment by WardBrian** [comment]
I’m still not sure what row wise sums mean in this context, since theta_rep in the model is a scalar

**Comment by mjhajharia** [comment]
mitzi is right, as i said, in the original stan file(check release 0.9’s
file instead of theta ‘y’ was used which was an N dimensional vector so
you’d have theta_rep[0] - theta_rep[10]

**Comment by mitzimorris** [comment]
@mjhajharia -  you mean 'y_rep[1] ... y_rep[10]', not 'theta_rep[0] ... theta_rep[10]' ?

Stan indexes from 1 (like a mathematician). whereas Python indexes from 0 (like a computer scientist).

'y_rep'  is the posterior predictive check - we use the estimate of 'theta' to generate new observations of y.

**Comment by WardBrian** [comment]
Ah, so at some point the model used here was changed to output only one value, which is already the sum of the the n trials. That makes sense as to why the post processing code looks like it did, but also why we can now do this in basically one line without any extra sums or anything. 

It looks like this file also tries to link to the Stan code used but the link fails. We should probably just do what we do in other notebooks and add a cell which is print(model.code()) to show it rather than a link which might break

**Comment by mitzimorris** [comment]
what model are we talking about - the model should be this one:  https://github.com/stan-dev/cmdstanpy/blob/develop/docsrc/examples/bernoulli_ppc.stan

**Comment by mjhajharia** [comment]
> what model are we talking about - the model should be this one: https://github.com/stan-dev/cmdstanpy/blob/develop/docsrc/examples/bernoulli_ppc.stan

this is the model the notebook takes as input, i think that's what causing issues?

**Comment by mitzimorris** [comment]
that datagen model makes no sense.

**Comment by mjhajharia** [comment]
> that datagen model makes no sense.

yep

**Comment by WardBrian** [comment]
`bernoulli_ppc` is used as the example in the "Generated Quantities" notebook, but as far as I can tell the MCMC notebook has always used `bernoulli_datagen` since it was added in https://github.com/stan-dev/cmdstanpy/pull/136

**Comment by mjhajharia** [comment]
> `bernoulli_ppc` is used as the example in the "Generated Quantities" notebook, but as far as I can tell the MCMC notebook has always used `bernoulli_datagen` since it was added in #136

yeah the original version of the datagen one was similar to the ppc one and then at some point some editing happened, either way i don't understand the stan model or purpose but if @mitzimorris can fix that i can definitely clean up the python part in the notebook

**Comment by WardBrian** [comment]
Yeah, looks like it changed in https://github.com/stan-dev/cmdstanpy/pull/277 

Is having a data generating model even a necessity for this notebook now that the standalone GQ notebook exists?

**Comment by mitzimorris** [comment]
the docs have expanded organically.  there's a tension between lightweight user's guide and worked examples and case studies, etc.   this was an issue in the beginning because we had to have "fixed_param" set.  now that's not necessary,
so the best thing to do is get rid of the datagen model here.

a datagen model belongs in its own section on prior predictive checks, SBC, etc.
I did a meetup a long time about about poisson vs neg binomial - that would be a reasonable example.

**Comment by mitzimorris** [comment]
@mjhajharia and @WardBrian - this notebook really needs cleaning up.
I started adding more to this as part of #555 - if it's OK with you, I'll continue doing so on that branch (https://github.com/stan-dev/cmdstanpy/tree/feature/555-compute-diagnostics)

**Comment by mitzimorris** [comment]
show off diagnostics.

**Pull request closed without merging**
