### PR TITLE
assemble draws and generated quantities only once

### PR DESCRIPTION
**Pull request by qres**
#### Submission Checklist

- [ ] Run unit tests
- [x] Declare copyright holder and open-source license: see below

#### Summary
Avoid loading the generated samples multiple times if multiple variables are accessed via `stan_variable('var_name')` which can take significant amount of time for large sample files. Unfortunately I had problems to run the unit test. Would somebody else run them, please?

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): University of Stuttgart

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by WardBrian** [comment]
Reading the code diff I am not sure why this is any different from the current behavior?

**Comment by qres** [comment]
The difference comes from lines as in [`stan_variable()`](https://github.com/stan-dev/cmdstanpy/blob/870cfe196bb9049fe29fe5dbe6793ca549ff92ef/cmdstanpy/stanfit/mcmc.py#L664) with a direct call to `_assemble_generated_quantities()` without a surrounding check whether the quantities have been assembled before.

**Comment by WardBrian** [comment]
Ah, which explains why it doesn't show up in the diff. Thanks for catching that. I think I'd prefer we add the if statement there rather than have the _assemble_draws function sometimes not assemble draws

**Comment by ahartikainen** [comment]
Hi, could someone please explain the logic?

I'm having a hard time understand the current changes. (Not saying they are wrong, I just wonder what is the correct way to not call that function more than once)

**Comment by WardBrian** [comment]
Thanks for this

**Pull request merged**
